CREATE SEQUENCE SEQ_COLLECT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TB_COLLECT (
    COLLECT_ID INTEGER DEFAULT SEQ_COLLECT.nextval NOT NULL,
    ADDRESS VARCHAR2(200) NOT NULL,
    COLLECT_TYPE VARCHAR2(200) NOT NULL,
    COLLECT_STATUS VARCHAR2(100) NOT NULL,
    SCHEDULED_DATE_TIME TIMESTAMP NOT NULL
)